MACRO command
	const \1_command
	DEF \1 EQUS "db \1_command"
ENDM

; BattleCommandPointers indexes (see data/battle/effect_command_pointers.asm)
	const_def 1
	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command moveanimnosub           ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command applydamage             ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command checkfaint              ; 11
	command buildopponentrage       ; 12
	command poisontarget            ; 13
	command sleeptarget             ; 14
	command draintarget             ; 15
	command eatdream                ; 16
	command burntarget              ; 17
	command freezetarget            ; 18
	command paralyzetarget          ; 19
	command selfdestruct            ; 1a
	command mirrormove              ; 1b
	command statup                  ; 1c
	command statdown                ; 1d
	command payday                  ; 1e
	command conversion              ; 1f
	command resetstats              ; 20
	command storeenergy             ; 21
	command unleashenergy           ; 22
	command forceswitch             ; 23
	command endloop                 ; 24
	command flinchtarget            ; 25
	command ohko                    ; 26
	command struggle                ; 27
	command recoil_1_3              ; 28
	command recoil_1_4              ; 29
	command mist                    ; 2a
	command focusenergy             ; 2b
	command confuse                 ; 2c
	command confusetarget           ; 2d
	command heal                    ; 2e
	command transform               ; 2f
	command screen                  ; 30
	command poison                  ; 31
	command paralyze                ; 32
	command substitute              ; 33
	command rechargenextturn        ; 34
	command mimic                   ; 35
	command metronome               ; 36
	command leechseed               ; 37
	command splash                  ; 38
	command disable                 ; 39
	command cleartext               ; 3a
	command charge                  ; 3b
	command checkcharge             ; 3c
	command traptarget              ; 3d
	command effect0x3c              ; 3e
	command rampage                 ; 3f
	command checkrampage            ; 40
	command constantdamage          ; 41
	command counter                 ; 42
	command encore                  ; 43
	command painsplit               ; 44
	command snore                   ; 45
	command conversion2             ; 46
	command lockon                  ; 47
	command sketch                  ; 48
	command defrostopponent         ; 49
	command sleeptalk               ; 4a
	command destinybond             ; 4b
	command spite                   ; 4c
	command falseswipe              ; 4d
	command healbell                ; 4e
	command kingsrock               ; 4f
	command triplekick              ; 50
	command kickcounter             ; 51
	command thief                   ; 52
	command arenatrap               ; 53
	command nightmare               ; 54
	command defrost                 ; 55
	command curse                   ; 56
	command protect                 ; 57
	command spikes                  ; 58
	command foresight               ; 59
	command perishsong              ; 5a
	command startsandstorm          ; 5b
	command endure                  ; 5c
	command checkrollout            ; 5d
	command rolloutpower            ; 5e
	command effect0x5d              ; 5f
	command furycutter              ; 60
	command attract                 ; 61
	command happinesspower          ; 62
	command present                 ; 63
	command damagecalc              ; 64
	command frustrationpower        ; 65
	command safeguard               ; 66
	command checksafeguard          ; 67
	command getmagnitude            ; 68
	command batonpass               ; 69
	command pursuit                 ; 6a
	command clearhazards            ; 6b
	command healmorn                ; 6c
	command healday                 ; 6d
	command healnite                ; 6e
	command hiddenpower             ; 6f
	command startrain               ; 70
	command startsun                ; 71
	command attackup                ; 72
	command defenseup               ; 73
	command speedup                 ; 74
	command specialattackup         ; 75
	command specialdefenseup        ; 76
	command accuracyup              ; 77
	command evasionup               ; 78
	command attackup2               ; 79
	command defenseup2              ; 7a
	command speedup2                ; 7b
	command specialattackup2        ; 7c
	command specialdefenseup2       ; 7d
	command accuracyup2             ; 7e
	command evasionup2              ; 7f
	command attackdown              ; 80
	command defensedown             ; 81
	command speeddown               ; 82
	command specialattackdown       ; 83
	command specialdefensedown      ; 84
	command accuracydown            ; 85
	command evasiondown             ; 86
	command attackdown2             ; 87
	command defensedown2            ; 88
	command speeddown2              ; 89
	command specialattackdown2      ; 8a
	command specialdefensedown2     ; 8b
	command accuracydown2           ; 8c
	command evasiondown2            ; 8d
	command statupmessage           ; 8e
	command statdownmessage         ; 8f
	command statupfailtext          ; 90
	command statdownfailtext        ; 91
	command effectchance            ; 92
	command statdownanim            ; 93
	command statupanim              ; 94
	command switchturn              ; 95
	command fakeout                 ; 96
	command bellydrum               ; 97
	command psychup                 ; 98
	command rage                    ; 99
	command doubleflyingdamage      ; 9a
	command doubleundergrounddamage ; 9b
	command mirrorcoat              ; 9c
	command checkfuturesight        ; 9d
	command futuresight             ; 9e
	command doubleminimizedamage    ; 9f
	command skipsuncharge           ; a0
	command thunderaccuracy         ; a1
	command teleport                ; a2
	command beatup                  ; a3
	command resettypematchup        ; a4
	command allstatsup              ; a5
	command bidefailtext            ; a6
	command raisesubnoanim          ; a7
	command lowersubnoanim          ; a8
	command beatupfailtext          ; a9
	command clearmissdamage         ; aa
	command movedelay               ; ab
	command moveanim                ; ac
	command tristatuschance         ; ad
	command supereffectivelooptext  ; ae
	command startloop               ; af
	command curl                    ; b0
	command defrosttarget           ; b1
	command weightdamage            ; b2
	command growth                  ; b3
DEF NUM_EFFECT_COMMANDS EQU const_value - 1

	const_def -1, -1
	command endmove                 ; ff
	command endturn                 ; fe
